config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  resources :comments

  resources :searches

  devise_for :users
  
  resources :listings do
    resources :orders
    resources :comments
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => "listings#seller"

  root 'listings#index'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	
	belongs_to :user
	has_many :orders
	has_many :comments
	belongs_to :category

	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :name, :description, :price, presence: true
	validates :price, numericality: { greater_than: 0}
	validates_attachment_presence :image

	def self.search(search)
		if search
			where(["lower(name) LIKE ?","%#{search}%"])
		end
		all
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  #This will prevent that a user type directly the url and get access to the pages.
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  #This will prevent that a user can change anything that doesn't belongs to the current user
  before_filter :check_user, only: [:edit, :update, :destroy]

  #The only listings that a user (seller) will see are those that belongs to the current user (owner)
  def seller
    @listings = Listing.search(params[:search])
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id #Adding the corresponding User to the Listing

    if current_user.recipient.blank?
      Stripe.api_key = ENV["stripe_api_key"]
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => current_user.name,
        :type => "individual",
        :bank_account => token
        )

      current_user.recipient = recipient.id
      current_user.save
    end
    

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category_id, :description, :price, :image)
    end

    # Validates that just the owner of the product can edit, update and destroy
    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="content-singin-form frm-new-pr">
    <h3 class="title-no-undeline">Create Product</h3>
      <%= form_for(@listing, html: { multipart: true }) do |f| %>
        <% if @listing.errors.any? %>
          <div id="error_explanation" class="alert alert-danger alert-dismissable custom-message-effect">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

            <ul>
            <% @listing.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div id="stripe-error" class="alert alert-danger" style="display:none;">
          <noscript>Please Enable Javascript</noscript>
        </div>
        
        <div class="form-group">
          <%= f.text_field :name, :placeholder => 'Product Name*', class: 'form-control input-login' %>
        </div>
        <div class="form-group">
          <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"}, {class: "btn btn-default dropdown-toggle select-purchase select-category-p"} %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, :placeholder => 'Product Description*', class: 'form-control input-login' %>
        </div>
        <div class="form-group">
          <%= f.text_field :price, :placeholder => 'Price*', class: 'form-control input-login' %>
        </div>
        <div class="form-group">
          <%= f.label :image %><br>
          <%= f.file_field :image, class: 'form-control select-purchase' %>
        </div>

        <% if current_user.recipient.blank? %>
          <hr>
          <h2>Bank Account Information</h2>
          <div class="form-group">
            <%= label_tag :country %>
            <%= text_field_tag :country, nil, {:name => nil, :'data-stripe' => "country", class: 'form-control select-purchase'} %>
          </div>
          <div class="form-group">
            <%= label_tag :routing_number %>
            <%= text_field_tag :routing_number, nil, {:name => nil, :'data-stripe' => "routingNumber", class: 'form-control select-purchase'} %>
          </div>
          <div class="form-group">
            <%= label_tag :account_number %>
            <%= text_field_tag :account_number, nil, {:name => nil, :'data-stripe' => "accountNumber", class: 'form-control select-purchase'} %>
          </div>

        <% end %>

        <div class="form-group">
          <div class="col-md-6 col-md-offset-3">
            <%= f.submit class: 'btn btn-log' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: 'btn btn-link' %> |
<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/index.html.erb
<!-- Carousel -->
<div id="main-carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#main-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#main-carousel" data-slide-to="1"></li>
    <li data-target="#main-carousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active item-main-slider-1 slide-it">
      <div class="slider-ct">
        <h4>Mackbook Pro 13''</h4>
        <p>$ 1,250.00</p>
        <%= link_to "Buy Now", new_listing_order_path(@listings), class: 'btn btn-main-slider'%>
      </div>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item item-main-slider-2 slide-it">
      <div class="slider-ct">
        <h4>Product Name</h4>
        <p>$ 250.00</p>
        <%= link_to "Buy Now", new_listing_order_path(@listings), class: 'btn btn-main-slider'%>
      </div>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item item-main-slider-3 slide-it">
      <div class="slider-ct">
        <h4>Product Name</h4>
        <p>$ 250.00</p>
        <%= link_to "Buy Now", new_listing_order_path(@listings), class: 'btn btn-main-slider'%>
      </div>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item item-main-slider-4 slide-it">
      <div class="slider-ct">
        <h4>Product Name</h4>
        <p>$ 250.00</p>
        <%= link_to "Buy Now", new_listing_order_path(@listings), class: 'btn btn-main-slider'%>
      </div>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item item-main-slider-5 slide-it">
      <div class="slider-ct">
        <h4>Product Name</h4>
        <p>$ 250.00</p>
        <%= link_to "Buy Now", new_listing_order_path(@listings), class: 'btn btn-main-slider'%>
      </div>
      <div class="carousel-caption">
      </div>
    </div>
  </div>

  <a class="left carousel-control control-mains" href="#main-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control control-mains" href="#main-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- Carousel -->

    <div class="row recent-deals-row">
      <div class="container">
        <h2 class="recent-title">Popular Products</h2>
          <% @listings[0..3].each_with_index.each do |listing| %>
          <div class="row-recent-products">
            <div class="col-md-3">
              <div class="thumbnail">
              <%= link_to image_tag(listing.image.url), listing %>
                <div class="caption">
                  <p class="short-description"><%= listing.description %></p>
                  <h3 class="title-recent-deals"> <%= number_to_currency(listing.price) %></h3>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>

<div class="container-fluid container-all-products">
<img class="logo-middle" src="https://s3.amazonaws.com/etsoniastorebucket/bg/logo-main.svg" alt="">
  <div id="products">
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-md-3 box-product">
          <div class="thumbnail thumbnail-various">
          <%= link_to image_tag(listing.image.url), listing %>
            <div class="caption">
              <h3><%= listing.name %></h3>
              <p> <%= number_to_currency(listing.price) %></p>
              <p class="short-description"><%= listing.description %></p>
              <p><%= listing.user.name%></p>
              <% if (user_signed_in?) && (current_user == listing.user) %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link' %>
  <% end %>

  <div class="row">
    <div class="fb-like" data-href="http://etsonia-store.herokuapp.com/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
  </div>

</div>

<script>
  $('#main-carousel').carousel({
    interval: 40000
});
</script>

app/views/listings/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/searches.html.erb
Sear

app/views/listings/seller.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Image</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Name</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Description</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Price</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Action</h4>
  </div>
</div>

<% @listings.each do |listing| %>
<div class="row">
  
  <div class="col-md-2 col-sm-6 col-xs-12">
    <%= image_tag listing.image.url, class: "img-responsive box-img-size" %>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h3><%= listing.name %></h3>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <p><%= listing.description %></p>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <p> <%= number_to_currency(listing.price) %></p>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Actions <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "View",  listing%></li>
        <li><%= link_to "Edit", edit_listing_path(listing)%></li>
        <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/listings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= image_tag @listing.image.url, class: 'img-responsive' %>	
		</div>
		<div class="col-md-6 description-item-container">
			<p>
			  <strong>Name:</strong>
			  <%= @listing.name %>
			</p>

			<p>
			  <strong>Price:</strong>
			  <%= @listing.price %>
			</p>

			<p>
			  <strong>Description:</strong>
			  <%= @listing.description %>
			</p>
			<p>
				<%= link_to "Buy Now", new_listing_order_path(@listing), class: 'btn btn-primary'%>
			</p>

			 <% if current_user == @listing.user %>
			  <%= link_to 'Edit', edit_listing_path(@listing) %> |
			 <% end %>

			<%= link_to 'Back', listings_path %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<h3 class="comments_title">
			  <%= @listing.comments.count %> Comments
			</h3>

			<div id="comments">
			  <%= render :partial => @listing.comments %>
			</div>
			<%= simple_form_for [@listing, Comment.new]  do |f| %>
			  <div class="field">
			    <%= f.text_area :body, class: "form-control input-login" %>
			  </div>
			  <br>
			  <div class="col-md-2 col-md-offset-4">
			  	<%= f.submit "Add Comment", class: "btn btn-log" %>
			  </div>
			<% end %>
		</div>
	</div>
	
</div>