config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  resources :comments

  resources :searches

  devise_for :users
  
  resources :listings do
    resources :orders
    resources :comments
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => "listings#seller"

  root 'listings#index'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  

end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-main">
  <div class="container-fluid container-navbar-main">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('https://s3.amazonaws.com/etsoniastorebucket/bg/logo-main.svg'), root_path, class: 'link-logo' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?%>
        <li class="dropdown dropdown-custom">
          <a href="#" class="dropdown-toggle dropdown-a" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-custom-menu">
            <li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
            <li><%= link_to 'Manage Listings', seller_path%></li>
            <li><%= link_to 'Sales History', sales_path%></li>
            <li><%= link_to 'Purchases History', purchases_path%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path%></li>
          <li><%= link_to 'Sign In', new_user_session_path%></li>
          <li><a href="#">About Us</a></li>
        <% end %>
      </ul>
      <%= form_tag searches_path, class: 'search-container navbar-form navbar-right', :method => 'get' do %>
          <%= text_field_tag :search, params[:search], class: 'search-box', id: 'search-box' %>
          <%= label_tag 'search-box' do %>
            <span class="glyphicon glyphicon-search search-icon"></span>
          <% end %>
          <%= submit_tag "Search", id: 'search-submit' %>
      <% end %>
    </div>
  </div>
</nav>