config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  resources :comments

  resources :searches

  devise_for :users
  
  resources :listings do
    resources :orders
    resources :comments
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => "listings#seller"

  root 'listings#index'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true
	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    # Finding the id in the url
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    #Filling the listing id column
    @order.listing_id = @listing.id
    # Field the buyer Id with the id of the currently signed user.
    @order.buyer_id = current_user.id
    #Filling the seller id column
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["stripe_api_key"]
    token = params[:stripeToken]

    begin

      customer = Stripe::Customer.create(source: params[:stripeToken])
 
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor, 
        :currency => "usd",
        :customer => customer.id
      )

      flash[:notice] = "Thanks for Ordering"
      rescue Stripe::CardError => e
        flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor, 
      :currency => "usd",
      :recipient => @seller.recipient
    )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <%= image_tag @listing.image.url, class: 'img-responsive' %>
      <h4><%= @listing.name%></h4>
      <h4><%= number_to_currency(@listing.price) %></h4>
    </div>

    <div class="col-md-7 content-singin-form1">
      <%= form_for([@listing, @order]) do |f| %>
        <% if @order.errors.any? %>
          <div id="error_explanation" class="alert alert-danger alert-dismissable custom-message-effect">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

            <ul>
            <% @order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div id="stripe-error" class="alert alert-danger" style="display:none;">
          <noscript>Please Enable Javascript</noscript>
        </div>

        <div class="form-group">
          <%= f.text_field :address, :placeholder => 'Address*', class: 'form-control input-login' %>
        </div>

        <div class="form-group">
          <%= f.text_field :city, :placeholder => 'City', class: 'form-control input-login' %>
        </div>

        <div class="form-group">
          <%= f.text_field :state, :placeholder => 'State', class: 'form-control input-login' %>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= text_field_tag :card_number, nil, {:name => nil, :placeholder => 'Credit Card Number', :'data-stripe' => "number", class: 'form-control input-login'} %>
          </div>
        </div>
          <div class="col-md-3">
              <div class="form-group">
                <%= text_field_tag :card_code, nil, {:name => nil, :placeholder => 'CVC', :'data-stripe' => "cvc", class: 'form-control input-login'} %>
              </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= select_month nil, {use_two_digit_numbers: true}, {:name => nil, :'data-stripe' => "exp-month", class: 'form-control select-purchase'} %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10 }, {:name => nil, :'data-stripe' => "exp-year", class: 'form-control select-purchase'} %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit 'Complete Order', class: 'btn btn-log' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', listing_orders_path %></td>
        <td><%= link_to 'Edit', edit_listing_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
 -->

app/views/orders/new.html.erb
<h3 class="recent-title">New Order</h3>

<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="container">
<h1>Sales History</h1>
  <div class="row">
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Image</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Item</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Price</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Customer</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Date Purchase</h4>
  </div>
</div>

<% @orders.each do |order| %>
  <div class="row">
    <div class="col-md-2 col-sm-6 col-xs-12">
      <%= image_tag order.listing.image.url(:thumb), class: "img-responsive" %>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <h3><%= order.listing.name %></h3>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <p> <%= number_to_currency(order.listing.price) %></p>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-12">
      <p><%= order.seller.name %></p>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-12">
     <p><%= order.created_at.strftime("%B %-d, %Y")%></p>
    </div>
  </div>
<% end %>
</div>

app/views/orders/sales.html.erb
<div class="container">
<h1>Sales History</h1>
  <div class="row">
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Image</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Item</h4>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h4>Price</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Customer</h4>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <h4>Date Sold</h4>
  </div>
</div>

<% @orders.each do |order| %>
<div class="row">
  <div class="col-md-2 col-sm-6 col-xs-12">
    <%= image_tag order.listing.image.url(:thumb), class: "img-responsive" %>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <h3><%= order.listing.name %></h3>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <p> <%= number_to_currency(order.listing.price) %></p>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
    <p><%= order.buyer.name %></p>
  </div>
  <div class="col-md-2 col-sm-6 col-xs-12">
   <p><%= order.created_at.strftime("%B %-d, %Y")%></p>
  </div>
</div>
<% end %>
</div>

app/views/orders/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>